services:
  - type: web
    name: GroceryAPP
    runtime: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHONUNBUFFERED
        value: true

  - type: pSQL
    name: groceryapp-db
    ipAllowList: []
    plan: free
